---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b4mad-racing-developer-hub-auth
  namespace: b4mad-racing-developer-hub-rhdh
spec:
  encryptedData:
    backend-secret: AgBaYbV0KN0VsBPa9oKf8SMJ+EkMoisKsLBCe7bacJNyH7r8A+GBtf7XIbixqYlHy9uUSpwDB47QD0eLEnVQijZ4GPY/96+OlQGA947FJkCVlDuVMcnmkSYG6oZ+fWvjwTqh5v/ksk/o0sUtmn36QOv0juwE5bEn7Vdjc28ZlqIusoCKQpneh4JiiBSeLQZV0F7WeJVXWUq3KH7Ik5Wiv6+91RSUZXgTeeJzJ8w4xPzwoJoQtFw+Y8CKEPZc7krumytB0NRYpt10v9XxU7AALhrY2x2gqgLm4BQ9pGSX1cBhlKl7X3L+Uddax5RKNWNEeVgtbSRMtlPp5Y4zctvvwXNqMlrTTfd6vdlsDTjxQVvOUyXOtt+wQVfb5VvX+O86m8MRN/rvzECs9Wz8lQdpaqPjAw2a4gw4SBeOruySeRl6OTNseupLc8P35vwmvv/dyoczzj531Kk0BSVGVC3FbQil3J+7F/bODlbwmrNiY7Vr06uPCZnaNOH56/57eDsoFWuqZyTBIjnOMcwI2INXCExj/dRd716CuG9ifxi7yMQGz1ioNk/pSv0q9UBLPVeMtEMzS0fl793Kw7EubanGXg+ya/c1t7+O7bg14hnWqtUZrg6MoXej86WKJLkHMhLNQDeQyxMc4XFMSdOd4AuanJHE4avhHYmUPvsH8NLL9GgZ4XHRq8xv4hKBU5eyWcV524Yf3tAwF1ysL/xtS3UgUJH6UH0U9AmCass=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: backstage
        app.kubernetes.io/instance: b4mad-racing-developer-hub
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: backstage
        helm.sh/chart: backstage-2.15.0
      name: b4mad-racing-developer-hub-auth
      namespace: b4mad-racing-developer-hub-rhdh
    type: Opaque
