---
# Source: backstage/charts/upstream/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: "b4mad-racing-developer-hub" 
  labels:
    app.kubernetes.io/name: backstage
    helm.sh/chart: upstream-1.9.1
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: backstage
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http-backend
      port: 7007
      targetPort: backend
      protocol: TCP
      nodePort: null  
  selector:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/component: backstage
