---
# Source: developer-hub/charts/upstream/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: b4mad-racing-developer-hub
  namespace: "b4mad-racing-developer-hub" 
  labels:
    app.kubernetes.io/name: developer-hub
    helm.sh/chart: upstream-1.8.0
    app.kubernetes.io/instance: b4mad-racing-developer-hub
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: backstage
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http-backend
      port: 7007
      targetPort: backend
      protocol: TCP
      nodePort: null  
  selector:
    app.kubernetes.io/name: developer-hub
    app.kubernetes.io/instance: b4mad-racing-developer-hub
    app.kubernetes.io/component: backstage
