---
# Source: developer-hub/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backstage-developer-hub-auth
  namespace: "b4mad-racing-developer-hub-rhdh"
  labels:
    app.kubernetes.io/name: developer-hub
    helm.sh/chart: developer-hub-1.1.0
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "1.1-97"
    app.kubernetes.io/component: backstage
  annotations:
type: Opaque
data:
  backend-secret: "WWhDemZvSXcxdlhPR0dTdG1vVTZ2YzNo"
